### ISSUE TITLE
 make this work with github copilot

### ISSUE THREAD

**Issue by Geczy** [yufeikang/raycast_api_proxy#15]
https://github.com/aaamoon/copilot-gpt4-service

not too much is required. have to add a custom base_url to openai initialization, and fix checking choices[0] in case its undefined

**Comment by yufeikang** [comment]
You can try to slightly modify the code to achieve that. Since GitHub Copilot does not provide an API, users have reported getting their accounts banned for using reverse-engineered APIs. So i don't plan to support it. 🙅‍♂️
