### ISSUE TITLE
想问下有没有 translator 的请求返回示例

### ISSUE THREAD

**Issue by zhuozhiyongde** [yufeikang/raycast_api_proxy#19]
如题，现有项目似乎不支持 translator 功能，这个应该也是在后端进行了鉴权什么的，估计要像 chat_completions 一样劫持然后修改返回格式

但是问题是没有返回示例，直接用 chat_completions 的流式返回也不行，想问下大佬有没有开 Pro 抓个包啥的（？

**Comment by zhuozhiyongde** [comment]
已解决。

这部分作者大佬也可以考虑是否要迁移一下？

我的实现在 https://github.com/zhuozhiyongde/Unlocking-Raycast-With-Surge/blob/7011f88cafc154215fd147a8a51930ee768e5638/app/main.py#L297-L402 是一个基于 OpenAI 的。

**Comment by yufeikang** [comment]
好的

**Comment by zhuozhiyongde** [comment]
大佬也可以看一下其他部分的实现 比如OpenAI的错误处理啥的（原谅我偷懒没交pr 2333

另外翻译其实可以看看要不要支持别的商业API 现在基于OpenAI的实现速度很慢，Raycast官方应该也不是OpenAI的，官方的很快，应该是商业API

**Comment by yufeikang** [comment]
已经支持了
