### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by ThinkFar** [yufeikang/raycast_api_proxy#20]
I setup the proxy using docker on my mac m1, but I still don't know how to access the AI. 

I added my OpenAI key and the container is running.

It still gives me the message "Upgrade to Pro" whenever I try to ask something.

Am I misunderstanding something?

**Comment by yufeikang** [comment]
You can try using mitm tools, like proxyman, to capture the traffic and confirm if raycast is correctly redirected to localhost. From the feedback of other users, it seems that the hosts file for IPv6 may not be effective on some devices. I'm not sure about the specific reason. Anyway, you can try to find out the cause. 👍

**Comment by yufeikang** [comment]
From the mitm tool, you can see the client ip. You can confirm if the host file resolves the domain of backend.raycast.com to your localhost ip. If convenient, you can screenshot it and I will help you analyze. 😊🔍

**Comment by ThinkFar** [comment]
I see that in the proxy script there is a possible typo of "mitmporxy" 

Is that correct, could this have potential issues?
