### ISSUE TITLE
Raycast 不会发请求到服务器，但本地可以

### ISSUE THREAD

**Issue by littleblack111** [yufeikang/raycast_api_proxy#24]
我没有surge. 所以我用/etc/hosts
本地：127.0.0.1 backend.raycast.com
我试过了本地docker部署（和服务器一摸一样的配置（cert 也一样））。可以用。
但我在服务器上部署的时候
远程：subdomain.domain.ltd(this is not my real domain)
我用nginx proxy manager. 12443(https)->443(subdomain)(https)不行(192.168.8.2 port 12443 -> subdomain.domain.tld+letsencrypt ssl certificate。服务器docker logs没有任何访问日志
direct local IP 也不行.(/etc/hosts: 192.168.8.2:12443 raycast.backend.com)
我吧self sign certificate放到keychain始终信任了

**Comment by yufeikang** [comment]
host file写错了。/etc/hosts: 192.168.8.2:12443 raycast.backend.com

host不支持端口号。host只是domain和ip的映射
