### ISSUE TITLE
无法更改默认 AI 模型

### ISSUE THREAD

**Issue by JasonY580** [yufeikang/raycast_api_proxy#33]
Hello @yufeikang 

我试图分叉你的的存储库并通过更改来更改 Raycast AI 的默认模型：`default_models = _get_default_model_dict("openai-gpt-3.5-turbo")` （自 main.py, 312 行）

这是我分叉的存储库：https://github.com/JasonY580/raycast_api_proxy

我将我自己的存储库版本推送到 Docker，然后通过 Aspen 进行測試，它似乎已更新：
<img width="600" alt="Screenshot 2024-06-09 at 11 55 12 AM" src="https://github.com/yufeikang/raycast_api_proxy/assets/83808447/305f7d8c-08f3-4b0d-8b7c-71a349159d71">

但是当我尝试在重新启动后运行 Raycast AI 时，它不起作用：
<img width="600" alt="Screenshot 2024-06-09 at 11 48 13 AM" src="https://github.com/yufeikang/raycast_api_proxy/assets/83808447/2dbf6f74-04b0-4de6-9839-3ff98cfbbeee">

**Comment by yufeikang** [comment]
sorry, 已经fix
