### ISSUE TITLE
Streaming support?

### ISSUE THREAD

**Issue by littleblack111** [yufeikang/raycast_api_proxy#41]
Please add streaming support. I personally don't know how it works but needing to wait until it output is a headake. thank you

**Comment by yufeikang** [comment]
Previously, I encountered an issue where I couldn't retrieve the function call's arguments when using stream output. Today, I discovered that the argument string is also streamed when using stream. So, this problem has been resolved. Thank you for your feedback, which prompted me to address this issue. 😊
