### ISSUE TITLE
依然显示订阅页面

### ISSUE THREAD

**Issue by fatwang2** [yufeikang/raycast_api_proxy#5]
本地host已修改，ping的时候已经提示服务器地址了，main.py也提示运行了，但是raycast依然显示订阅页面，请问能否把部署方案写的更详细一些，不知道哪里出错了

**Comment by yufeikang** [comment]
试试把ipv6也加上

::1             backend.raycast.com

如果OK请反馈一下

**Comment by fatwang2** [comment]
这个是也已经加了的

**Comment by fatwang2** [comment]
很想使用这个项目，但是一直没成功，今天用docker部署了一遍还是没成功。我是在我的vps上配置的docker，看日志运行正常。同时mac本地的hosts改成了vps的ip地址，证书也安装成功。打开raycast的时候还是提示引导订阅  @yufeikang

**Comment by yufeikang** [comment]
请问打开raycast的时候，docker的log上有访问日志吗

**Comment by fatwang2** [comment]
您好，没有的，这就是我我困惑的地方，请求根本没转发过去

**Comment by yufeikang** [comment]
提供一个思路排查问题。目前你这边的状况似乎是host文件没有生效。建议尝试以下步骤：

1. 执行：`sudo killall -HUP mDNSResponder`
2. 执行：`ping backend.raycast.com`
    确认ping的的ip是否是预期的ip

**Comment by fatwang2** [comment]
您好，我在本地计算机ping这个地址，得到的确实是我部署了代理的vps地址，目前docker处于运行中状态，但是依然是显示订阅页面

**Comment by yufeikang** [comment]
方便的话发我一下你的部署命令：`a291LnVoaS54QGdtYWlsLmNvbQo=`

**Comment by yufeikang** [comment]
尝试增加：
```
::1   backend.raycast.com
```

我发现ipv6的host有时候会不生效。具体原因未知

**Comment by nohzafk** [comment]
一样的情况，dns已修改，ping域名也是显示是本地IP了，但是容器就是没有收到请求

**Comment by yufeikang** [comment]
建议你使用抓包工具排查一下吧。这种情况还没遇到过
