### ISSUE TITLE
A way to support the project?

### ISSUE THREAD

**Issue by dmitrybabich** [yufeikang/raycast_api_proxy#50]
The project is so great! Thank you! I would be happy to support it with at least a one-time payment. Consider adding a tip jar or something to support the project.

**Comment by yufeikang** [comment]
Thank you so much for your kind words and support! 🎉 We’re thrilled to hear that you find the project valuable. We truly appreciate your willingness to contribute.

If you’d like to make a donation, you can support the project through this link: [GitHub Sponsors](https://github.com/sponsors/yufeikang).

Thank you once again for your generosity and support!
