### ISSUE TITLE
Can I use this to defer to a local OpenAI compatible API?

### ISSUE THREAD

**Issue by kirel** [yufeikang/raycast_api_proxy#52]
If yes, please add docs!

**Comment by XLHJiang** [comment]
Do you know aide? Its API looks like this:{
  "aide.openaiBaseUrl": "https://api.zyai.online/v1",
  "aide.openaiKey": "API key",
  "aide.openaiModel": "gpt-4o"
}
How can I modify this to use the API?
I am deeply grateful.

**Comment by yufeikang** [comment]
Now, we've added support for providers compatible with the OpenAI API. Please refer to the README for more details. 😊
