### ISSUE TITLE
升级Raycast到1.61.1，AI对话，后面会加上“the data could't be read because it is missing”

### ISSUE THREAD

**Issue by miosx** [yufeikang/raycast_api_proxy#7]
升级Raycast到1.61.1，AI对话，后面会加上“the data could't be read because it is missing”

<img width="662" alt="image" src="https://github.com/yufeikang/raycast_api_proxy/assets/131627176/de37c50a-18a7-44d5-8018-1a60a8150d4f">

**Comment by yufeikang** [comment]
我测试了没问题。你可以贴一下docker的日志吗
